### ISSUE TITLE
Mac 版本如何操作？

### ISSUE THREAD

**Issue by faydanube** [Koiii367/LOL1#3]
老哥，Mac 要怎麼操作？台服 riot 客戶端只有台灣和馬來，沒有簡體中文，翻譯不對很煩。

<img width="752" alt="image" src="https://github.com/user-attachments/assets/fe314e90-0c29-4f04-93c9-f29f29736b9a">
<img width="877" alt="image" src="https://github.com/user-attachments/assets/8b174a22-51db-4547-a58a-6846327d7ff4">

**Comment by Koiii367** [comment]
没有做macos的适配（不会） 不好意思

**Comment by faydanube** [comment]
@Koiii367 感謝回復
